name: a1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  flutter_randomcolor: ^1.0.14

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sensors_plus: ^3.1.0
  flutter_map: ^6.0.1
  # flutter_map_heatmap: ^1.0.5
  permission_handler: ^11.0.1

  flutter_map_location_marker: ^8.0.1
  flutter_map_heatmap: ^0.0.7
  geodesy: ^0.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
